require "pry"

require "colorize"; stations = { "N" => ["Times Square", "34th", "28th", "23rd", "Union Square", "8th"],"L" => ["8th", "6th", "Union Square", "3rd", "1st"],"6" => ["Grand Central", "33rd", "28th", "23rd", "Union Square", "Astor Place"],:stops => 0}; puts "Welcome to MTA!".light_green; puts "Which line are you starting at?".light_blue; start_line = gets.chomp; puts "Which station are you starting at?".light_blue; start_station = gets.chomp; puts "Which line are you departing at?".light_blue; exit_line = gets.chomp; puts "Which station are you departing at?".light_blue; exit_station = gets.chomp; if start_line == exit_line; stops = stations[start_line].index(start_station) < stations[start_line].index(exit_station) ? stations[start_line][((stations[start_line].index start_station) + 1)..(stations[start_line].index exit_station)] : stations[start_line][(stations[start_line].index exit_station)..((stations[start_line].index start_station) - 1)].reverse; puts "Travel on the #{start_line} line for the following stops: ".light_magenta; puts stops; stations[:stops] += stops.size; puts "Arrive at #{exit_station}".green; puts "Total stops: #{stations[:stops]}".green; end

# def plan_trip (start_line, start_station, end_line, end_station) @stations[:stops] = 0; return describe_trip start_line, start_station, end_station, end_station if start_line == end_line; describe_trip start_line, start_station, "Union Square", end_station; describe_trip end_line, "Union Square", end_station, end_station; puts "Total stops: #{@stations[:stops]}".green; puts "Thanks for using MTA!".light_blue; puts ("-=" * 40).light_blue end

# def describe_trip (line, start, destination, end_trip) index_of_boarding, index_of_alight = @stations[line].index(start), @stations[line].index(destination); puts "Travel on the #{line} line for the following stops:".green; stops = index_of_boarding > index_of_alight ? @stations[line][index_of_alight..index_of_boarding - 1].reverse : @stations[line][index_of_boarding + 1..index_of_alight]; puts stops; @stations[:stops] += stops.size; puts end_trip != "Union Square" && destination == "Union Square" ? "Change at Union Square.".light_magenta : "Arrive at #{destination}.".green end

# def user_inputs (question_string) puts "Which #{question_string} at?".light_blue; output = gets.chomp end


